import { dir } from 'i18next';
import { languages } from '../../i18n/settings';
import { Roboto } from 'next/font/google';
import './globals.css';

const robotoFont = Roboto({
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return languages.map((locale) => ({ locale }));
}

export default function RootLayout({ children, params: { locale } }) {
  return (
    <html lang={locale} dir={dir(locale)}>
      <body className={robotoFont.className}>{children}</body>
    </html>
  );
}
